<?php
include('header.php');
require_once '../dbconn.php';
$sql="SELECT YEAR(FROM_UNIXTIME(dateTime)) year,MONTH(FROM_UNIXTIME(dateTime)) month,ROUND(AVG(windSpeed)*3.6,1) avg_speed,ROUND(MAX(windGust)*3.6,1) max_gust,SUBSTRING_INDEX(GROUP_CONCAT(windGustDir ORDER BY windGust DESC),',',1) gust_dir FROM archive WHERE windSpeed IS NOT NULL GROUP BY year,month ORDER BY year,month";
$result=db_query($sql);$data=$years=$monthlyHighAvg=$monthlyLowAvg=$monthlyHighGust=$monthlyLowGust=[];$peak=['value'=>null,'year'=>null,'month'=>null,'dir'=>null];$archiveAvgSum=0;$archiveAvgCount=0;
while($row=mysqli_fetch_assoc($result)){$y=(int)$row['year'];$m=(int)$row['month'];$avg=(float)$row['avg_speed'];$gust=(float)$row['max_gust'];$dir=$row['gust_dir']===null?null:(float)$row['gust_dir'];$data[$y][$m]=['avg'=>$avg,'gust'=>$gust,'dir'=>$dir];$years[$y]=true;$archiveAvgSum+=$avg;$archiveAvgCount++;
 $monthlyHighAvg[$m]=isset($monthlyHighAvg[$m])?max($monthlyHighAvg[$m],$avg):$avg;$monthlyLowAvg[$m]=isset($monthlyLowAvg[$m])?min($monthlyLowAvg[$m],$avg):$avg;$monthlyHighGust[$m]=isset($monthlyHighGust[$m])?max($monthlyHighGust[$m],$gust):$gust;$monthlyLowGust[$m]=isset($monthlyLowGust[$m])?min($monthlyLowGust[$m],$gust):$gust;if($peak['value']===null||$gust>$peak['value'])$peak=['value'=>$gust,'year'=>$y,'month'=>$m,'dir'=>$dir];}
mysqli_free_result($result);$years=array_keys($years);sort($years);$latestYear=end($years);$latest=$data[$latestYear]??[];$latestAvg=$latest?array_sum(array_column($latest,'avg'))/count($latest):null;
$series=[];foreach($years as $year){$avgPoints=[];$gustPoints=[];for($m=1;$m<=12;$m++){$avgPoints[]=$data[$year][$m]['avg']??null;$gustPoints[]=$data[$year][$m]['gust']??null;}$visible=$year>=$latestYear-2;$series[]=['name'=>$year.' average','data'=>$avgPoints,'type'=>'spline','visible'=>$visible,'year'=>$year];$series[]=['name'=>$year.' peak','data'=>$gustPoints,'type'=>'spline','dashStyle'=>'ShortDash','visible'=>$visible,'year'=>$year,'linkedTo'=>':previous'];}
function compassPoint($degrees){if($degrees===null)return '—';$points=['N','NE','E','SE','S','SW','W','NW'];return $points[(int)round($degrees/45)%8];}
?>
<main class="annual-workspace">
 <header class="annual-header"><div><span class="annual-eyebrow">Annual reports · Wind</span><h1>Wind yearbook</h1><p>Compare monthly mean wind, peak gusts and gust bearings across the station archive.</p></div><nav class="annual-switcher" aria-label="Annual report type"><a href="/reporttempyeartotals.php"><i class="fas fa-temperature-half"></i> Temperature</a><a href="/reportrainyeartotals.php"><i class="fas fa-cloud-rain"></i> Rain</a><a aria-current="page" href="/reportwindyeartotals.php"><i class="fas fa-wind"></i> Wind</a></nav></header>
 <section class="annual-kpis"><div class="annual-kpi" style="--kpi-accent:#0891b2"><span>Archive monthly mean</span><strong><?php echo $archiveAvgCount?number_format($archiveAvgSum/$archiveAvgCount,1):'—';?></strong><small>kph</small></div><div class="annual-kpi" style="--kpi-accent:#2762a5"><span><?php echo $latestYear;?> mean to date</span><strong><?php echo $latestAvg===null?'—':number_format($latestAvg,1);?></strong><small>kph</small></div><div class="annual-kpi" style="--kpi-accent:#d97738"><span>Archive peak gust</span><strong><?php echo $peak['value']===null?'—':number_format($peak['value'],1);?></strong><small>kph</small></div><div class="annual-kpi" style="--kpi-accent:#6d5bd0"><span>Peak bearing</span><strong><?php echo compassPoint($peak['dir']);?></strong><small><?php echo $peak['dir']===null?'':number_format($peak['dir'],0).'° · '.date('M',mktime(0,0,0,$peak['month'],10)).' '.$peak['year'];?></small></div></section>
 <section class="annual-chart-panel"><div class="annual-panel-header"><div><h2>Monthly wind profile</h2><p>Average and peak gust in kph · latest three years shown</p></div></div><div id="annual-wind-chart" class="annual-chart"></div></section>
 <section class="annual-table-panel"><div class="annual-panel-header"><div><h2>Monthly wind detail</h2><p>Average / peak gust / gust bearing · monthly extremes are highlighted</p></div></div><div class="annual-table-scroll"><table class="annual-table"><thead><tr><th class="month-cell" rowspan="2">Month</th><?php foreach($years as $year){?><th colspan="3"><?php echo $year;?></th><?php }?></tr><tr><?php foreach($years as $year){?><th>Avg kph</th><th>Peak kph</th><th>Bearing</th><?php }?></tr></thead><tbody><?php for($m=1;$m<=12;$m++){?><tr><td class="month-cell"><?php echo date('F',mktime(0,0,0,$m,10));?></td><?php foreach($years as $year){$v=$data[$year][$m]??null;if(!$v){?><td>—</td><td>—</td><td>—</td><?php }else{?><td class="<?php echo $v['avg']===$monthlyHighAvg[$m]?'is-high':($v['avg']===$monthlyLowAvg[$m]?'is-low':'');?>"><?php echo number_format($v['avg'],1);?></td><td class="<?php echo $v['gust']===$monthlyHighGust[$m]?'is-high':($v['gust']===$monthlyLowGust[$m]?'is-low':'');?>"><?php echo number_format($v['gust'],1);?></td><td><?php echo $v['dir']===null?'—':compassPoint($v['dir']).' '.number_format($v['dir'],0).'°';?></td><?php }}?></tr><?php }?></tbody></table></div></section>
</main>
<script>document.addEventListener('DOMContentLoaded',function(){Highcharts.chart('annual-wind-chart',{chart:{backgroundColor:'transparent',spacing:[16,12,8,8]},title:{text:null},xAxis:{categories:<?php echo json_encode(array_map(fn($m)=>date('M',mktime(0,0,0,$m,10)),range(1,12)));?>},yAxis:{title:{text:'Wind speed (kph)'},min:0},tooltip:{shared:true,valueSuffix:' kph'},legend:{align:'center',verticalAlign:'bottom'},plotOptions:{series:{marker:{enabled:false},lineWidth:2,connectNulls:false}},series:<?php echo json_encode($series);?>,responsive:{rules:[{condition:{maxWidth:620},chartOptions:{yAxis:{title:{text:null}},legend:{itemStyle:{fontSize:'9px'}}}}]}});});</script>
<?php include('footer.php');?>
