<?php
include('header.php');
require_once '../dbconn.php';
$sql="SELECT YEAR(FROM_UNIXTIME(dateTime)) AS \"year\", MONTH(FROM_UNIXTIME(dateTime)) AS \"month\", ROUND(SUM(rain)*10,1) total FROM archive GROUP BY \"year\",\"month\" ORDER BY \"year\",\"month\"";
$result=db_query($sql); $data=$years=$totals=$monthCounts=[]; $monthlyHigh=$monthlyLow=[]; $wettestMonth=['value'=>null,'year'=>null,'month'=>null];
while($row=db_fetch_assoc($result)){
  $year=(int)$row['year'];$month=(int)$row['month'];$value=(float)$row['total'];
  $data[$year][$month]=$value;$years[$year]=true;$totals[$year]=($totals[$year]??0)+$value;$monthCounts[$year]=($monthCounts[$year]??0)+1;
  $monthlyHigh[$month]=isset($monthlyHigh[$month])?max($monthlyHigh[$month],$value):$value;$monthlyLow[$month]=isset($monthlyLow[$month])?min($monthlyLow[$month],$value):$value;
  if($wettestMonth['value']===null||$value>$wettestMonth['value'])$wettestMonth=['value'=>$value,'year'=>$year,'month'=>$month];
}
db_free_result($result);$years=array_keys($years);sort($years);$latestYear=end($years);$completeTotals=array_filter($totals,fn($v,$y)=>($monthCounts[$y]??0)===12,ARRAY_FILTER_USE_BOTH);
$wettestYear=$completeTotals?array_search(max($completeTotals),$completeTotals,true):null;$driestYear=$completeTotals?array_search(min($completeTotals),$completeTotals,true):null;
$series=[];foreach($years as $year){$points=[];for($m=1;$m<=12;$m++)$points[]=$data[$year][$m]??null;$series[]=['name'=>(string)$year,'data'=>$points,'visible'=>$year>=$latestYear-3];}
?>
<main class="annual-workspace">
 <header class="annual-header"><div><span class="annual-eyebrow">Annual reports · Rainfall</span><h1>Rainfall yearbook</h1><p>Monthly totals, annual accumulation and archive rainfall extremes in millimetres.</p></div><nav class="annual-switcher" aria-label="Annual report type"><a href="/reporttempyeartotals.php"><i class="fas fa-temperature-half"></i> Temperature</a><a aria-current="page" href="/reportrainyeartotals.php"><i class="fas fa-cloud-rain"></i> Rain</a><a href="/reportwindyeartotals.php"><i class="fas fa-wind"></i> Wind</a></nav></header>
 <section class="annual-kpis"><div class="annual-kpi" style="--kpi-accent:#2586c4"><span><?php echo $latestYear; ?> total to date</span><strong><?php echo number_format($totals[$latestYear]??0,1); ?></strong><small>mm</small></div><div class="annual-kpi" style="--kpi-accent:#174f78"><span>Wettest full year</span><strong><?php echo $wettestYear??'—'; ?></strong><small><?php echo $wettestYear?number_format($completeTotals[$wettestYear],0).' mm':''; ?></small></div><div class="annual-kpi" style="--kpi-accent:#73a9ca"><span>Driest full year</span><strong><?php echo $driestYear??'—'; ?></strong><small><?php echo $driestYear?number_format($completeTotals[$driestYear],0).' mm':''; ?></small></div><div class="annual-kpi" style="--kpi-accent:#6d5bd0"><span>Wettest month</span><strong><?php echo $wettestMonth['month']?date('M',mktime(0,0,0,$wettestMonth['month'],10)).' '.$wettestMonth['year']:'—'; ?></strong><small><?php echo $wettestMonth['value']===null?'':number_format($wettestMonth['value'],1).' mm'; ?></small></div></section>
 <section class="annual-chart-panel"><div class="annual-panel-header"><div><h2>Monthly rainfall comparison</h2><p>Latest four years shown · toggle archive years in the legend</p></div></div><div id="annual-rain-chart" class="annual-chart"></div></section>
 <section class="annual-table-panel"><div class="annual-panel-header"><div><h2>Monthly accumulation</h2><p>Millimetres · wettest and driest values for each calendar month are highlighted</p></div></div><div class="annual-table-scroll"><table class="annual-table"><thead><tr><th class="month-cell">Month</th><?php foreach($years as $year){?><th><?php echo $year;?></th><?php }?></tr></thead><tbody><?php for($m=1;$m<=12;$m++){?><tr><td class="month-cell"><?php echo date('F',mktime(0,0,0,$m,10));?></td><?php foreach($years as $year){$v=$data[$year][$m]??null;?><td class="<?php echo $v!==null&&$v===$monthlyHigh[$m]?'is-high':($v!==null&&$v===$monthlyLow[$m]?'is-low':'');?>"><?php echo $v===null?'—':number_format($v,1);?></td><?php }?></tr><?php }?><tr class="total-row"><td class="month-cell">Annual total</td><?php foreach($years as $year){?><td><?php echo number_format($totals[$year]??0,1);?></td><?php }?></tr></tbody></table></div></section>
</main>
<script>document.addEventListener('DOMContentLoaded',function(){WeatherCharts.chart('annual-rain-chart',{chart:{type:'column',backgroundColor:'transparent',spacing:[16,12,8,8]},title:{text:null},xAxis:{categories:<?php echo json_encode(array_map(fn($m)=>date('M',mktime(0,0,0,$m,10)),range(1,12)));?>},yAxis:{title:{text:'Rainfall (mm)'},min:0},tooltip:{shared:true,valueSuffix:' mm'},legend:{align:'center',verticalAlign:'bottom'},plotOptions:{column:{borderWidth:0,borderRadius:3,groupPadding:.1,pointPadding:.04}},series:<?php echo json_encode($series);?>,responsive:{rules:[{condition:{maxWidth:620},chartOptions:{yAxis:{title:{text:null}},legend:{itemStyle:{fontSize:'10px'}}}}]}});});</script>
<?php include('footer.php');?>
